---
-   hosts: 127.0.0.1
    connection: local
    become: yes
    remote_user: root
    vars:
      UPFNS : "UPFns"
      EXEC_UPFNS : "sudo -E ip netns exec UPFns"
      UENS: "UEns"
      GTPBindAddress: "10.200.200.2"
      AMFSCTPAddresses: "10.200.200.1"
      IKEBindAddress: "192.168.127.1"
      INTERFACES_GREs:
        - { name: 'gre0' }

      INTERFACES_XFRMIs:
        - { name: 'xfrm-4' }
        - { name: 'xfrm-3' }
        - { name: 'xfrm-2' }
        - { name: 'xfrm-1' }
        - { name: 'xfrm-0' }

    tasks:


      #Remove N3IWF Interfaces
      - name: Remove GRE Interfaces
        shell: sudo ip link del {{ item.name }}
        loop: "{{ INTERFACES_GREs }}"
        loop_control:
          index_var: gre_interface_idx
        ignore_errors: true

      - name: Remove XFRM Interfaces
        shell: sudo ip link del {{ item.name }}
        loop: "{{ INTERFACES_XFRMIs }}"
        loop_control:
          index_var: xfrm_interface_idx
        ignore_errors: true

      - name: Delete config
        shell: |
          sudo killall -15 upf 
          sudo ip link del veth0
          sudo ip netns del {{ UPFNS }}
          sudo ip addr del 10.60.0.1/32 dev lo
        ignore_errors: true