---
-   hosts: 127.0.0.1
    connection: local
    become: yes
    remote_user: root
    vars:
      UPFNS : "UPFns"
      EXEC_UPFNS : "sudo -E ip netns exec UPFns"
      UENS: "UEns"
      GTPBindAddress : "10.200.200.2"
      AMFSCTPAddresses : "10.200.200.1"
      IKEBindAddress : "192.168.127.1"
      INTERFACES_GREs:
        - { name: 'gre0' }

      INTERFACES_XFRMIs:
        - { name: 'xfrm0' }

    tasks:


      #1º Clear Old config

      #Remove N3IWF Interfaces
      - name: Remove GRE Interfaces
        shell: sudo ip link del {{ item.name }}
        loop: "{{ INTERFACES_GREs }}"
        loop_control:
          index_var: gre_interface_idx
        ignore_errors: true

      - name: Remove XFRM Interfaces
        shell: sudo ip link del {{ item.name }}
        loop: "{{ INTERFACES_XFRMIs }}"
        loop_control:
          index_var: xfrm_interface_idx
        ignore_errors: true

      - name: Delete config
        shell: |
          sudo killall -15 upf 
          sudo ip link del veth0
          sudo ip netns del {{ UPFNS }}
          sudo ip addr del 10.60.0.1/32 dev lo
        ignore_errors: true

      #2º Config N3IWF param
      - name: Init config
        shell: |
          sudo ip netns add {{ UPFNS }}
          sudo ip link add veth0 type veth peer name veth1
          sudo ip link set veth0 up
          sudo ip addr add 10.60.0.1 dev lo
          sudo ip addr add {{ AMFSCTPAddresses }}/24 dev veth0
          sudo ip addr add {{ GTPBindAddress }}/24 dev veth0
          sudo ip link set veth1 netns {{ UPFNS }}
          {{ EXEC_UPFNS }} ip link set lo up
          {{ EXEC_UPFNS }} ip link set veth1 up
          {{ EXEC_UPFNS }} ip addr add 10.60.0.101 dev lo
          {{ EXEC_UPFNS }} ip addr add 10.200.200.101/24 dev veth1
          {{ EXEC_UPFNS }} ip addr add 10.200.200.102/24 dev veth1
          
          sudo ip xfrm policy flush
          sudo ip xfrm state flush
        ignore_errors: true

      # ATENÇÂO - bem aqui tem o Start da UPF com configFile de teste
      # seguido de um sleep de 2 segundos


      #Setup N3UEEnv
      - name: Setup N3UE_env
        shell: |
          sudo ip netns add {{ UENS }} 
          sudo ip link add veth2 type veth peer name veth3
          sudo ip addr add {{ IKEBindAddress }}/24 dev veth2
          sudo ip link set veth2 up
          sudo ip link set veth3 netns {{ UENS }}
          
          sudo -E ip netns exec {{ UENS }} ip addr add 192.168.127.2/24 dev veth3
          sudo -E ip netns exec {{ UENS }} ip link set lo up
          sudo -E ip netns exec {{ UENS }} ip link set veth3 up